:- multifile attributetype/3.

childrentyping(select,"(optgroup|option)+").
attributetype(select,id,VALUE).
attributetype(select,class,VALUE).
attributetype(select,style,VALUE).
attributetype(select,title,VALUE).
attributetype(select,lang,VALUE).
attributetype(select,xml:lang,VALUE).
attributetype(select,dir,VALUE):-VALUE==ltr;VALUE==rtl.
attributetype(select,onclick,VALUE).
attributetype(select,ondblclick,VALUE).
attributetype(select,onmousedown,VALUE).
attributetype(select,onmouseup,VALUE).
attributetype(select,onmouseover,VALUE).
attributetype(select,onmousemove,VALUE).
attributetype(select,onmouseout,VALUE).
attributetype(select,onkeypress,VALUE).
attributetype(select,onkeydown,VALUE).
attributetype(select,onkeyup,VALUE).
attributetype(select,name,VALUE).
attributetype(select,size,VALUE):-number(VALUE).
attributetype(select,multiple,VALUE).
attributetype(select,disabled,VALUE).
attributetype(select,tabindex,VALUE):-number(VALUE).
attributetype(select,onfocus,VALUE).
attributetype(select,onblur,VALUE).
attributetype(select,onchange,VALUE).
attributetype(option,id,VALUE).
attributetype(option,class,VALUE).
attributetype(option,style,VALUE).
attributetype(option,title,VALUE).
attributetype(option,lang,VALUE).
attributetype(option,xml:lang,VALUE).
attributetype(option,dir,VALUE):-VALUE==ltr;VALUE==rtl.
attributetype(option,onclick,VALUE).
attributetype(option,ondblclick,VALUE).
attributetype(option,onmousedown,VALUE).
attributetype(option,onmouseup,VALUE).
attributetype(option,onmouseover,VALUE).
attributetype(option,onmousemove,VALUE).
attributetype(option,onmouseout,VALUE).
attributetype(option,onkeypress,VALUE).
attributetype(option,onkeydown,VALUE).
attributetype(option,onkeyup,VALUE).
attributetype(option,selected,VALUE).
attributetype(option,disabled,VALUE).
attributetype(option,label,VALUE).
attributetype(option,value,VALUE).
attributetype(textarea,id,VALUE).
attributetype(textarea,class,VALUE).
attributetype(textarea,style,VALUE).
attributetype(textarea,title,VALUE).
attributetype(textarea,lang,VALUE).
attributetype(textarea,xml:lang,VALUE).
attributetype(textarea,dir,VALUE):-VALUE==ltr;VALUE==rtl.
attributetype(textarea,onclick,VALUE).
attributetype(textarea,ondblclick,VALUE).
attributetype(textarea,onmousedown,VALUE).
attributetype(textarea,onmouseup,VALUE).
attributetype(textarea,onmouseover,VALUE).
attributetype(textarea,onmousemove,VALUE).
attributetype(textarea,onmouseout,VALUE).
attributetype(textarea,onkeypress,VALUE).
attributetype(textarea,onkeydown,VALUE).
attributetype(textarea,onkeyup,VALUE).
attributetype(textarea,accesskey,VALUE).
attributetype(textarea,tabindex,VALUE):-number(VALUE).
attributetype(textarea,onfocus,VALUE).
attributetype(textarea,onblur,VALUE).
attributetype(textarea,name,VALUE).
attributetype(textarea,rows,VALUE):-number(VALUE).
attributetype(textarea,cols,VALUE):-number(VALUE).
attributetype(textarea,disabled,VALUE).
attributetype(textarea,readonly,VALUE).
attributetype(textarea,onselect,VALUE).
attributetype(textarea,onchange,VALUE).
attributetype(input,id,VALUE).
attributetype(input,class,VALUE).
attributetype(input,style,VALUE).
attributetype(input,title,VALUE).
attributetype(input,lang,VALUE).
attributetype(input,xml:lang,VALUE).
attributetype(input,dir,VALUE):-VALUE==ltr;VALUE==rtl.
attributetype(input,onclick,VALUE).
attributetype(input,ondblclick,VALUE).
attributetype(input,onmousedown,VALUE).
attributetype(input,onmouseup,VALUE).
attributetype(input,onmouseover,VALUE).
attributetype(input,onmousemove,VALUE).
attributetype(input,onmouseout,VALUE).
attributetype(input,onkeypress,VALUE).
attributetype(input,onkeydown,VALUE).
attributetype(input,onkeyup,VALUE).
attributetype(input,accesskey,VALUE).
attributetype(input,tabindex,VALUE):-number(VALUE).
attributetype(input,onfocus,VALUE).
attributetype(input,onblur,VALUE).
attributetype(input,type,VALUE):-VALUE==text;VALUE==password;VALUE==checkbox;VALUE==radio;VALUE==submit;VALUE==reset;VALUE==file;VALUE==hidden;VALUE==image;VALUE==button.
attributetype(input,name,VALUE).
attributetype(input,value,VALUE).
attributetype(input,checked,VALUE).
attributetype(input,disabled,VALUE).
attributetype(input,readonly,VALUE).
attributetype(input,size,VALUE).
attributetype(input,maxlength,VALUE):-number(VALUE).
attributetype(input,src,VALUE).
attributetype(input,alt,VALUE).
attributetype(input,usemap,VALUE).
attributetype(input,onselect,VALUE).
attributetype(input,onchange,VALUE).
attributetype(input,accept,VALUE).
